services:
  laminas:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    environment:
      DB_HOST: db
      DB_DATABASE: "test_db"
      DB_USERNAME: admin
      DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "test_db"
      # MYSQL_USER: admin
      # MYSQL_PASSWORD: "uvgPXG%3o%&7Xad0yb"
      TZ: Africa/Tunis
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 128M
    ports:
      - "8880:80"
    depends_on:
      - db

volumes:
  db_data: